Fix(OAuth): fix google login
KUIT-MAPU/MAPU-Backend pull request #43
Opened 2024-07-23 09:00 UTC by rlawngP91

Resolves #42 

## 📌 개요

google 유저정보 가져오는 부분에서 오류발견 수정함
google 유저정보로 추가정보로 입력하는 과정에서 email과 platform id의 column설정이 너무 작게 되어 있어 수정함

## 📝 PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더 삭제

## ✔ PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-07-23 10:31 UTC, yunjeongiya requested changes
바로 고쳐져서 다행이네요! .DS_Store 파일들 gitignore 추가해서 내려주신 후에 머지하면 좋을 것 같습니다!

2024-07-23 10:31 UTC, yunjeongiya commented on .DS_Store
gitignore에 .DS_store 추가해야 할 것 같습니다!

2024-07-23 10:31 UTC, yunjeongiya commented on src/main/java/com/mapu/infra/oauth/google/GoogleUserService.java
> +    public GoogleToken getAccessToken(String code) {
👍👍

2024-07-23 16:11 UTC, yeonjookang approved these changes
LGTM!

2024-07-23 16:11 UTC, yeonjookang commented on src/main/java/com/mapu/infra/oauth/google/GoogleUserService.java
> +    public GoogleToken getAccessToken(String code) {
오류 찾느라 고생하셨습니다 :)

2024-07-24 04:57 UTC, yunjeongiya commented
LGTM!

2024-07-24 05:00 UTC, yunjeongiya approved these changes

2024-07-24 05:01 UTC, merged

2024-07-24 05:02 UTC, ssilver01 reviewed
LGTM!